#!/bin/bash
echo -e "\e[92mAllow\e[0m"
#echo -e "\e[91mDisallow\e[0m   \e[95m[ \e[96mExit Now \e[95m] " && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 100 && sleep 50 && sleep 50 && sleep 50 && sleep 50 && sleep 50 && sleep 50 && sleep
